import ReactQueryProvider from "@/providers/ReactQueryProvider";

import type { Metadata } from "next";
import "./globals.css";
import { geist } from "@/fonts";
import { IdentityProvider } from "@/providers/IdentityProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={geist.variable}>
      <body>
        <ReactQueryProvider>
          <IdentityProvider>{children}</IdentityProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
