import type { Metadata } from "next";
import "./globals.css";
import { geist } from "@/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={geist.variable}
    >
      <body>{children}</body>
    </html>
  );
}
