import ReactQueryProvider from "@/shared/providers/ReactQueryProvider";

import type { Metadata } from "next";
import "./globals.css";
import { geist } from "@/fonts";
import { SocketProvider } from "@/shared/providers/SocketProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={geist.variable}>
      <body>
        <ReactQueryProvider>
          <SocketProvider>{children}</SocketProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
